project:
  type: website

website:
  title: "Neurowissenschaft Computerlab"
  navbar:
    background: primary
    left:
      - text: Admin
        menu:
          - pages/admin/overview.qmd
          - pages/admin/assessments.qmd
    right:
      - text: Kapitel
        menu:
          - pages/chapters/03_data_cleaning.qmd
  page-footer:
    left: "© Copyright 2022, Andrew Ellis"
    right:
      - icon: github
        href: https://github.com/

format:
  html:
    theme: cosmo
    css: styles.css
