project:
  type: website
  output-dir: docs

website:
  title: "Neurowissenschaft Computerlab"
  site-url: https://kogpsy.github.io/neuroscicomplab_fs22_quarto/
  navbar:
    logo: /assets/logo.png
    background: primary
    left:
      - text: Admin
        menu:
          - pages/admin/01_overview.qmd
          - pages/admin/02_assessments.qmd
          - pages/admin/03_zulip_forum.qmd
    right:
      - text: Kapitel
        menu:
          - pages/chapters/03_data_cleaning.qmd
  page-footer:
    left: "© Copyright 2022, Andrew Ellis"
    right:
      - icon: github
        href: https://github.com/kogpsy/neuroscicomplab_fs22_quarto

format:
  html:
    theme:
      light: [flatly, styles/light.scss]
      dark: [darkly, styles/dark.scss]
    css: /styles/global.css
